groups:
- name: Registers
  rules:
  - alert: RequestsExcess5xx
    expr: sum(increase(requests{job="openregister-metric-exporter",status_range="5xx"}[5m])) by (app) >= 3
    for: 15s
    annotations:
        summary: "Service has too many 5xx errors"
        description: "Service {{ $labels.app }} has had too many 5xx errors."
