global:
  scrape_interval: 30s
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['10.0.0.38:9093']
rule_files:
  - "/etc/prometheus/alerts/*"
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: paas-targets
    scheme: http
    proxy_url: 'http://paas-proxy:8080'
    file_sd_configs:
      - files: ['/etc/prometheus/targets/*.json']
        refresh_interval: 30s
